--ENable TDE on DATABASENAME encrypting with server assymetric Key

use DATABASENAME
go
CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM =AES_256 ENCRYPTION BY SERVER ASYMMETRIC KEY <KEY_NAME>
go
ALTER DATABASE DATABASENAME SET ENCRYPTION ON
Go


--ENable TDE on DATABASENAME encrypting with server certificate

use DATABASENAME
go
CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM =AES_256 ENCRYPTION BY SERVER certificate <Certificate_NAME>
go
ALTER DATABASE DATABASENAME SET ENCRYPTION ON
Go
