ALTER DATABASE CURRENT SET COMPATIBILITY_LEVEL = 160; -- for SQL 2022
ALTER DATABASE CURRENT SET AUTO_CREATE_STATISTICS ON;
ALTER DATABASE CURRENT SET AUTO_UPDATE_STATISTICS ON;
 
-- PERMISSION: Requires ALTER ANY DATABASE SCOPED CONFIGURATION on the database. 
-- This permission can be granted by a user with CONTROL permission on a database.
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 1;
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = ON;
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = ON;
go
DBCC TRACEON (10054, -1);
GO
